Первая итерация
PhilippNikitin/go-rest-api-homework pull request #1
Opened 2024-07-30 10:48 UTC by PhilippNikitin

2024-07-30 14:56 UTC, just-musha requested changes
Привет! Отличная работа, хорошая стркутура кода. Предлагаю проверить ошибки и добавить одну проверку, и работа будет принята.

2024-07-30 14:56 UTC, just-musha commented on internal/handlers/handlers.go
> +	w.Write(resp)
Лучше явно проверить ошибку которую возвращает Write, достаточно будет залогировать в консоль

2024-07-30 14:56 UTC, just-musha commented on internal/handlers/handlers.go
> +	db.Tasks[task.ID] = task
Здесь стоит проверить есть ли уже тако IT, если да - вернуть ошикбу ползователю. Иначе задача будет перезатерта

2024-07-30 14:56 UTC, just-musha commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Это ошибка сервера, нужно сменить статус код

2024-07-30 14:56 UTC, just-musha commented on internal/handlers/handlers.go
> +	w.Write(resp)
Проверить ошибку нужно тоже явно и залогировать

2024-07-30 14:56 UTC, just-musha commented on internal/models/models.go
> +type Task struct {
Грамотная организация кода - респект :+1:

2024-07-30 21:52 UTC, PhilippNikitin commented
> Привет! Отличная работа, хорошая стркутура кода. Предлагаю проверить ошибки и добавить одну проверку, и работа будет принята.

Привет! Большое спасибо за ревью и замечания, постарался все поправить.

2024-07-31 10:45 UTC, just-musha approved these changes
Супер. Еще пару коментов оставила, уже не критично. Принято! Успехов дальше.

2024-07-31 10:45 UTC, just-musha commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Можно не вызывать http.Error, тк если была проблема с записью w, а http.Error тоже внутри Write вызывает. Достаточно в лог записать и все

2024-07-31 10:45 UTC, just-musha commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Аналогично тут

2024-07-31 10:45 UTC, just-musha commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Ещё кстати такой момент - если ошибка сервера - не рекомендуюется возвращать саму ошибку, в целях безопасности. Как вариант - вернуть "ошибка сервера", а саму `err` залогировать

2024-08-01 06:27 UTC, merged